In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r'C:\Users\piyus\Downloads\egrid2018_data_v2.xlsx',header=[0, 1], sheet_name='PLNT18')

In [3]:
df

,eGRID2018 Plant file sequence number,Data Year,Plant state abbreviation,Plant name,DOE/EIA ORIS plant or facility code,Plant transmission or distribution system owner name,Plant transmission or distribution system owner ID,Utility name,Utility ID,Plant-level sector,...,Plant wind generation percent (resource mix),Plant solar generation percent (resource mix),Plant geothermal generation percent (resource mix),Plant other fossil generation percent (resource mix),Plant other unknown / purchased fuel generation percent (resource mix),Plant total nonrenewables generation percent (resource mix),Plant total renewables generation percent (resource mix),Plant total nonhydro renewables generation percent (resource mix),Plant total combustion generation percent (resource mix),Plant total noncombustion generation percent (resource mix)
,SEQPLT18,YEAR,PSTATABB,PNAME,ORISPL,OPRNAME,OPRCODE,UTLSRVNM,UTLSRVID,SECTOR,...,PLWIPR,PLSOPR,PLGTPR,PLOFPR,PLOPPR,PLTNPR,PLTRPR,PLTHPR,PLCYPR,PLCNPR
0,1,2018,AK,7-Mile Ridge Wind Project,60814,Alaska Power and Telephone Co,219,Alaska Power and Telephone Co,219,Electric Utility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2018,AK,Agrium Kenai Nitrogen Operations,54452,Homer Electric Assn Inc,19558,Agrium US Inc,179,Industrial CHP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2018,AK,Alakanuk,57053,"Alaska Village Elec Coop, Inc",221,"Alaska Village Elec Coop, Inc",221,Electric Utility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2018,AK,Allison Creek Hydro,58982,"Copper Valley Elec Assn, Inc",4329,"Copper Valley Elec Assn, Inc",4329,Electric Utility,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,5,2018,AK,Ambler,60243,"Alaska Village Elec Coop, Inc",221,"Alaska Village Elec Coop, Inc",221,Electric Utility,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10959,10960,2018,WY,Western Sugar Coop - Torrington,57967,City of Torrington - (WY),19032,Western Sugar Cooperative,57315,Industrial CHP,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
10960,10961,2018,WY,Wygen I,55479,Black Hills Power Inc,19545,"Black Hills Power, Inc. d/b/a",19545,IPP Non-CHP,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
10961,10962,2018,WY,Wygen II,56319,Black Hills Power Inc,19545,"Black Hills Power, Inc. d/b/a",19545,Electric Utility,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
10962,10963,2018,WY,Wygen III,56596,Black Hills Power Inc,19545,"Black Hills Power, Inc. d/b/a",19545,Electric Utility,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
10963,10964,2018,WY,Wyodak,6101,PacifiCorp,14354,PacifiCorp,14354,Electric Utility,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [4]:
data=df[[('Plant state abbreviation','PSTATABB'),('Plant name','PNAME'),('Plant latitude','LAT'),('Plant longitude','LON'),('Plant annual net generation (MWh)','PLNGENAN'),('Plant annual coal net generation (MWh)','PLGENACL'),('Plant annual oil net generation (MWh)','PLGENAOL'),('Plant annual gas net generation (MWh)','PLGENAGS'),('Plant annual nuclear net generation (MWh)','PLGENANC'),('Plant annual hydro net generation (MWh)','PLGENAHY'),('Plant annual biomass net generation (MWh)','PLGENABM'),('Plant annual wind net generation (MWh)','PLGENAWI'),('Plant annual solar net generation (MWh)','PLGENASO'),('Plant annual geothermal net generation (MWh)','PLGENAGT'),('Plant annual other fossil net generation (MWh)','PLGENAOF'),('Plant annual other unknown/ purchased fuel net generation (MWh)','PLGENAOP'),('Plant annual total nonrenewables net generation (MWh)','PLGENATN'),('Plant annual total renewables net generation (MWh)','PLGENATR'),('Plant coal generation percent (resource mix)','PLCLPR'),('Plant oil generation percent (resource mix)','PLOLPR'),('Plant gas generation percent (resource mix)','PLGSPR'),('Plant nuclear generation percent (resource mix)','PLNCPR'),('Plant hydro generation percent (resource mix)','PLHYPR'),('Plant biomass generation percent (resource mix)','PLBMPR'),('Plant wind generation percent (resource mix)','PLWIPR'),('Plant solar generation percent (resource mix)','PLSOPR'),('Plant geothermal generation percent (resource mix)','PLGTPR'),('Plant other fossil generation percent (resource mix)','PLOFPR'),('Plant other unknown / purchased fuel generation percent (resource mix)','PLOPPR'),('Plant total nonrenewables generation percent (resource mix)','PLTNPR'),('Plant total renewables generation percent (resource mix)','PLTRPR')]]

In [5]:
other = data[('Plant annual other fossil net generation (MWh)','PLGENAOF')] + data[('Plant annual other unknown/ purchased fuel net generation (MWh)','PLGENAOP')]

In [6]:
data[('Plant other net generation (MWh)'),('PLGENAOO')] = other

C:\Users\piyus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [7]:
data

,Plant state abbreviation,Plant name,Plant latitude,Plant longitude,Plant annual net generation (MWh),Plant annual coal net generation (MWh),Plant annual oil net generation (MWh),Plant annual gas net generation (MWh),Plant annual nuclear net generation (MWh),Plant annual hydro net generation (MWh),...,Plant hydro generation percent (resource mix),Plant biomass generation percent (resource mix),Plant wind generation percent (resource mix),Plant solar generation percent (resource mix),Plant geothermal generation percent (resource mix),Plant other fossil generation percent (resource mix),Plant other unknown / purchased fuel generation percent (resource mix),Plant total nonrenewables generation percent (resource mix),Plant total renewables generation percent (resource mix),Plant other net generation (MWh)
,PSTATABB,PNAME,LAT,LON,PLNGENAN,PLGENACL,PLGENAOL,PLGENAGS,PLGENANC,PLGENAHY,...,PLHYPR,PLBMPR,PLWIPR,PLSOPR,PLGTPR,PLOFPR,PLOPPR,PLTNPR,PLTRPR,PLGENAOO
0,AK,7-Mile Ridge Wind Project,63.210689,-143.247156,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AK,Agrium Kenai Nitrogen Operations,60.673200,-151.378400,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AK,Alakanuk,62.683300,-164.654400,0.000,0.00,0.000,0.000,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,AK,Allison Creek Hydro,61.084444,-146.353333,23077.000,0.00,0.000,0.000,0.0,23077.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,AK,Ambler,67.087980,-157.856719,1205.999,0.00,1206.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10959,WY,Western Sugar Coop - Torrington,42.046900,-104.186300,6262.320,0.00,0.000,6262.320,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10960,WY,Wygen I,44.285800,-105.383300,639452.000,638162.24,0.000,1289.762,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10961,WY,Wygen II,44.291900,-105.381100,769549.000,768460.92,0.000,1088.084,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10962,WY,Wygen III,44.291900,-105.380600,852015.000,850379.23,0.000,1635.775,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10963,WY,Wyodak,44.290128,-105.381482,2251976.000,2250043.10,1932.888,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [8]:
data=data.drop(columns=[('Plant annual other fossil net generation (MWh)','PLGENAOF'), ('Plant annual other unknown/ purchased fuel net generation (MWh)','PLGENAOP')])

In [9]:
other1 = data[('Plant other fossil generation percent (resource mix)','PLOFPR')] + data[('Plant other unknown / purchased fuel generation percent (resource mix)','PLOPPR')]

In [10]:
data[('Plant other generation percent (resource mix)','PLOOPR')]= other1

In [11]:
data=data.drop(columns=[('Plant other fossil generation percent (resource mix)','PLOFPR'), ('Plant other unknown / purchased fuel generation percent (resource mix)','PLOPPR')])

In [12]:
data

,Plant state abbreviation,Plant name,Plant latitude,Plant longitude,Plant annual net generation (MWh),Plant annual coal net generation (MWh),Plant annual oil net generation (MWh),Plant annual gas net generation (MWh),Plant annual nuclear net generation (MWh),Plant annual hydro net generation (MWh),...,Plant nuclear generation percent (resource mix),Plant hydro generation percent (resource mix),Plant biomass generation percent (resource mix),Plant wind generation percent (resource mix),Plant solar generation percent (resource mix),Plant geothermal generation percent (resource mix),Plant total nonrenewables generation percent (resource mix),Plant total renewables generation percent (resource mix),Plant other net generation (MWh),Plant other generation percent (resource mix)
,PSTATABB,PNAME,LAT,LON,PLNGENAN,PLGENACL,PLGENAOL,PLGENAGS,PLGENANC,PLGENAHY,...,PLNCPR,PLHYPR,PLBMPR,PLWIPR,PLSOPR,PLGTPR,PLTNPR,PLTRPR,PLGENAOO,PLOOPR
0,AK,7-Mile Ridge Wind Project,63.210689,-143.247156,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AK,Agrium Kenai Nitrogen Operations,60.673200,-151.378400,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AK,Alakanuk,62.683300,-164.654400,0.000,0.00,0.000,0.000,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,AK,Allison Creek Hydro,61.084444,-146.353333,23077.000,0.00,0.000,0.000,0.0,23077.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,AK,Ambler,67.087980,-157.856719,1205.999,0.00,1206.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10959,WY,Western Sugar Coop - Torrington,42.046900,-104.186300,6262.320,0.00,0.000,6262.320,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10960,WY,Wygen I,44.285800,-105.383300,639452.000,638162.24,0.000,1289.762,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10961,WY,Wygen II,44.291900,-105.381100,769549.000,768460.92,0.000,1088.084,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10962,WY,Wygen III,44.291900,-105.380600,852015.000,850379.23,0.000,1635.775,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10963,WY,Wyodak,44.290128,-105.381482,2251976.000,2250043.10,1932.888,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [13]:
data.to_excel(r'C:\Users\piyus\Downloads\2018sort.xlsx')

In [14]:
states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}

In [15]:
data[('Plant state abbreviation','PSTATABB')].unique()

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
       'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object)

In [16]:
len(states)

57

In [17]:
data[('Plant state abbreviation','PSTATABB')] = df[('Plant state abbreviation','PSTATABB')].map(states).fillna(df[('Plant state abbreviation','PSTATABB')])

In [18]:
data

,Plant state abbreviation,Plant name,Plant latitude,Plant longitude,Plant annual net generation (MWh),Plant annual coal net generation (MWh),Plant annual oil net generation (MWh),Plant annual gas net generation (MWh),Plant annual nuclear net generation (MWh),Plant annual hydro net generation (MWh),...,Plant nuclear generation percent (resource mix),Plant hydro generation percent (resource mix),Plant biomass generation percent (resource mix),Plant wind generation percent (resource mix),Plant solar generation percent (resource mix),Plant geothermal generation percent (resource mix),Plant total nonrenewables generation percent (resource mix),Plant total renewables generation percent (resource mix),Plant other net generation (MWh),Plant other generation percent (resource mix)
,PSTATABB,PNAME,LAT,LON,PLNGENAN,PLGENACL,PLGENAOL,PLGENAGS,PLGENANC,PLGENAHY,...,PLNCPR,PLHYPR,PLBMPR,PLWIPR,PLSOPR,PLGTPR,PLTNPR,PLTRPR,PLGENAOO,PLOOPR
0,Alaska,7-Mile Ridge Wind Project,63.210689,-143.247156,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alaska,Agrium Kenai Nitrogen Operations,60.673200,-151.378400,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alaska,Alakanuk,62.683300,-164.654400,0.000,0.00,0.000,0.000,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,Alaska,Allison Creek Hydro,61.084444,-146.353333,23077.000,0.00,0.000,0.000,0.0,23077.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,Alaska,Ambler,67.087980,-157.856719,1205.999,0.00,1206.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10959,Wyoming,Western Sugar Coop - Torrington,42.046900,-104.186300,6262.320,0.00,0.000,6262.320,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10960,Wyoming,Wygen I,44.285800,-105.383300,639452.000,638162.24,0.000,1289.762,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10961,Wyoming,Wygen II,44.291900,-105.381100,769549.000,768460.92,0.000,1088.084,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10962,Wyoming,Wygen III,44.291900,-105.380600,852015.000,850379.23,0.000,1635.775,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10963,Wyoming,Wyodak,44.290128,-105.381482,2251976.000,2250043.10,1932.888,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [19]:
data.to_excel(r'C:\Users\piyus\Downloads\2018sort.xlsx')

In [20]:
df2 = pd.read_excel(r'C:\Users\piyus\Downloads\2000.xls', sheet_name='EGRDPLNT00')

In [21]:
df2

,SEQPLT00\neGRID2002 2000 file plant sequence number,SEQPLT99\neGRID2002 1999 file plant sequence number,PSTATABB,PNAME,ORISPL\nDOE/EIA ORIS plant or facility code,PLTYPE\nPlant type,PREVUTIL\nPreviously a utility plant flag,"CHANGE\nChange? – If Y, go to EGRDPLCH file",OPRNAME\nPlant operator name,OPRCODE\nPlant operator ID,...,OWNRUC13\nPlant 2000 owner code (thirteenth),OWNRPR13\nPlant 2000 owner percent (thirteenth),OWNRTY13\nPlant 2000 owner type (thirteenth),OWNRNM14\nPlant 2000 owner name (fourteenth),OWNRUC14\nPlant 2000 owner code (fourteenth),OWNRPR14\nPlant 2000 owner percent (fourteenth),OWNRTY14\nPlant 2000 owner type (fourteenth),SEQPLT\neGRID96 1996 file plant sequence number,SEQPLT97\neGRID97 1997 file plant sequence number,SEQPLT98\neGRID2000 1998 file plant sequence number
0,1,2.0,AK,AGRIUM KENAI NITROGEN OPERATIONS,54452.0,NU,0,N,Agrium Kenai Nitrogen Operatio,179.0,...,0,0.0,NaN,NaN,0,0.0,NaN,71.0,70.0,2.0
1,2,1.0,AK,ALAKANUK,6308.0,UT,0,N,Alaska Village Elec Coop Inc,221.0,...,0,0.0,NaN,NaN,0,0.0,NaN,1.0,1.0,1.0
2,3,NaN,AK,ALLAKAKET,7750.0,UT,0,N,Alaska Power Co,219.0,...,0,0.0,NaN,NaN,0,0.0,NaN,NaN,NaN,NaN
3,4,3.0,AK,ALYESKA SEAFOODS INC,54222.0,NU,0,N,Alyeska Seafoods Inc,431.0,...,0,0.0,NaN,NaN,0,0.0,NaN,2.0,2.0,3.0
4,5,4.0,AK,AMBLER,6556.0,UT,0,N,Alaska Village Elec Coop Inc,221.0,...,0,0.0,NaN,NaN,0,0.0,NaN,3.0,3.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4696,4697,4611.0,WY,SINCLAIR OIL REFINERY,54374.0,NU,0,N,Sinclair Oil Corp,24205.0,...,0,0.0,NaN,NaN,0,0.0,NaN,4844.0,4810.0,4632.0
4697,4698,4612.0,WY,SPIRIT MOUNTAIN,7541.0,UT,0,N,USBR-Great Plains Region,19567.0,...,0,0.0,NaN,NaN,0,0.0,NaN,4845.0,4811.0,4633.0
4698,4699,4613.0,WY,STRAWBERRY CREEK,6393.0,UT,0,N,Lower Valley Energy Inc,11273.0,...,0,0.0,NaN,NaN,0,0.0,NaN,4846.0,4812.0,4634.0
4699,4700,4614.0,WY,VIVA NAUGHTON,7050.0,UT,0,N,PacifiCorp-East,14354.1,...,0,0.0,NaN,NaN,0,0.0,NaN,4848.0,4814.0,4635.0
4700,4701,4615.0,WY,WYODAK,6101.0,UT,0,N,PacifiCorp-East,14354.1,...,0,0.0,NaN,NaN,0,0.0,NaN,4849.0,4815.0,4636.0

In [22]:
d= df2.columns

In [23]:
for a in d:
    print(a)

SEQPLT00
eGRID2002 2000 file plant sequence number
SEQPLT99
eGRID2002 1999 file plant sequence number
PSTATABB
PNAME
ORISPL
DOE/EIA ORIS plant or facility code
PLTYPE
Plant type
PREVUTIL
Previously a utility plant flag
CHANGE
Change? – If Y, go to EGRDPLCH file
OPRNAME
Plant operator name
OPRCODE
Plant operator ID
UTLSRVNM
Nonutility's service area name
UTLSRVID
Nonutility's service area ID
OPPRNUM
Location (operator)-based parent company ID
OPPRNAME
Location (operator)-based parent company name
PCANAME
Location (operator)-based power control area name
PCAID
Location (operator)-based power control area ID
NERC
Location (operator)-based NERC region acronym
NERCNUM
NERC number associated with NERC region
SUBRGN
eGRID subregion acronym
SRNAME
eGRID subregion name
FIPST
Plant FIPS State code
FIPSCNY
Plant FIPS county code
CNTYNAME
Plant county name
LAT
LON
NUMBLR
Number of utility boilers
NUMGEN
Number of generators
SOURCEM
Plant emissions source(s)
PLPRIMFL
Plant primary fuel
PLFFLCTG
Plant fossil fuel category
CAPFAC
Plant capacity factor
BOILCAP
Utility plant boiler capacity (MMBtu/hr)
NAMEPCAP
Plant generator capacity (MW)
CHPFLAG
Combined heat and power (CHP) (cogenerator) 2000 plant flag
USETHRMO
CHP plant 2000 useful thermal output (MMBtu)
PWRTOHT
CHP plant 2000 power to heat ratio
ELCALLOC
CHP plant 2000 electric allocation factor
PLNUCONN
Nonutility plant connected to grid flag
PSFLG
Plant pumped storage flag
ARDBNU
ARD nonutility flag
LMSWFLG
Nonutility plant landfill methane or solid waste flag
PLNUCMBS
Plant nonutility combustion flag
PLNUCOAL
Plant nonutility coal flag
UTNOWNU
Now nonutility flag
GENERVAL
Generation value source
EMISVAL
Emission value source
RESMXVAL
Resource mix value source
PLHTIAN
Plant 2000 annual heat input (MMBtu)
PLHTIOZ
Plant 2000 ozone season heat input (MMBtu)
PLGGENAN
Plant 2000 annual gross generation (MWh)
PLNGENAN
PLNGENOZ
Plant 2000 ozone season net generation (MWh)
PLNOXAN
Plant 2000 annual NOx emissions (tons)
PLNOXOZ
Plant 2000 ozone season NOx emissions (tons)
PLSO2AN
Plant 2000 annual SO2 emissions (tons)
PLCO2AN
Plant 2000 annual CO2 emissions (tons)
PLHGAN
Plant 2000 annual mercury emissions (lbs)
PLNOXRTA
Plant 2000 annual NOx output emission rate (lbs/MWh)
PLNOXRTO
Plant 2000 ozone season NOx output emission rate (lbs/MWh)
PLSO2RTA
Plant 2000 annual SO2 output emission rate (lbs/MWh)
PLCO2RTA
Plant 2000 annual CO2 output emission rate (lbs/MWh)
PLHGRTA
Plant 2000 annual mercury output emission rate (lbs/GWh)
PLNOXRA
Plant 2000 annual NOx input emission rate (lbs/MMBtu)
PLNOXRO
Plant 2000 ozone season NOx input emission rate (lbs/MMBtu)
PLSO2RA
Plant 2000 annual SO2 input emission rate (lbs/MMBtu)
PLCO2RA
Plant 2000 annual CO2 input emission rate (lbs/MMBtu)
PLHGRA
Plant 2000 annual mercury input emission rate (lbs/BBtu)
PLHTRT
Plant 2000 nominal heat rate (Btu/kWh)
PLGENACL
PLGENAOL
PLGENAGS
PLGENANC
PLGENAHY
PLGENABM
PLGENAWI
PLGENASO
PLGENAGT
PLGENAOF
PLGENASW
PLGENATN
PLGENATR
PLGENATH
Plant 2000 annual total nonhydro renewables net generation (MWh)
PLCLPR
PLOLPR
PLGSPR
PLNCPR
PLHYPR
PLBMPR
PLWIPR
PLSOPR
PLGTPR
PLOFPR
PLSWPR
PLTNPR
PLTRPR
PLTHPR
Plant 2000 total nonhydro renewables generation percent (resource mix)
OWNRNM01
Plant 2000 owner name (first)
OWNRUC01
Plant 2000 owner code (first)
OWNRPR01
Plant 2000 owner percent (first)
OWNRTY01
Plant 2000 owner type (first)
OWNRNM02
Plant 2000 owner name (second)
OWNRUC02
Plant 2000 owner code (second)
OWNRPR02
Plant 2000 owner percent (second)
OWNRTY02
Plant 2000 owner type (second)
OWNRNM03
Plant 2000 owner name (third)
OWNRUC03
Plant 2000 owner code (third)
OWNRPR03
Plant 2000 owner percent (third)
OWNRTY03
Plant 2000 owner type (third)
OWNRNM04
Plant 2000 owner name (fourth)
OWNRUC04
Plant 2000 owner code (fourth)
OWNRPR04
Plant 2000 owner percent (fourth)
OWNRTY04
Plant 2000 owner type (fourth)
OWNRNM05
Plant 2000 owner name (fifth)
OWNRUC05
Plant 2000 owner code (fifth)
OWNRPR05
Plant 2000 owner percent (fifth)
OWNRTY05
Plant 2000 owner type (fifth)
OWNRNM06
Plant 2000 owner name (sixth)
OWNRUC06
Plant 2000 owner code (sixth)
OWNRPR06
Plant 2000 owner percent (sixth)
OWNRTY06
Plant 2000 owner type (sixth)
OWNRNM07
Plant 2000 owner name (seventh)
OWNRUC07
Plant 2000 owner code (seventh)
OWNRPR07
Plant 2000 owner percent (seventh)
OWNRTY07
Plant 2000 owner type (seventh)
OWNRNM08
Plant 2000 owner name (eighth)
OWNRUC08
Plant 2000 owner code (eighth)
OWNRPR08
Plant 2000 owner percent (eighth)
OWNRTY08
Plant 2000 owner type (eighth)
OWNRNM09
Plant 2000 owner name (ninth)
OWNRUC09
Plant 2000 owner code (ninth)
OWNRPR09
Plant 2000 owner percent (ninth)
OWNRTY09
Plant 2000 owner type (ninth)
OWNRNM10
Plant 2000 owner name (tenth)
OWNRUC10
Plant 2000 owner code (tenth)
OWNRPR10
Plant 2000 owner percent (tenth)
OWNRTY10
Plant 2000 owner type (tenth)
OWNRNM11
Plant 2000 owner name (eleventh)
OWNRUC11
Plant 2000 owner code (eleventh)
OWNRPR11
Plant 2000 owner percent (eleventh)
OWNRTY11
Plant 2000 owner type (eleventh)
OWNRNM12
Plant 2000 owner name (twelfth)
OWNRUC12
Plant 2000 owner code (twelfth)
OWNRPR12
Plant 2000 owner percent (twelfth)
OWNRTY12
Plant 2000 owner type (twelfth)
OWNRNM13
Plant 2000 owner name (thirteenth)
OWNRUC13
Plant 2000 owner code (thirteenth)
OWNRPR13
Plant 2000 owner percent (thirteenth)
OWNRTY13
Plant 2000 owner type (thirteenth)
OWNRNM14
Plant 2000 owner name (fourteenth)
OWNRUC14
Plant 2000 owner code (fourteenth)
OWNRPR14
Plant 2000 owner percent (fourteenth)
OWNRTY14
Plant 2000 owner type (fourteenth)
SEQPLT
eGRID96 1996 file plant sequence number
SEQPLT97
eGRID97 1997 file plant sequence number
SEQPLT98
eGRID2000 1998 file plant sequence number

In [24]:
data2000 = df2[['PSTATABB','PNAME','LAT','LON','PLNGENAN','PLGENACL','PLGENAOL','PLGENAGS','PLGENANC','PLGENAHY','PLGENABM','PLGENAWI','PLGENASO','PLGENAGT','PLGENAOF','PLGENASW','PLGENATN','PLGENATR','PLCLPR','PLOLPR','PLGSPR','PLNCPR','PLHYPR','PLBMPR','PLWIPR','PLSOPR','PLGTPR','PLOFPR','PLSWPR','PLTNPR','PLTRPR']]

In [25]:
other1 = data2000['PLGENAOF'] + data2000['PLGENASW']

In [26]:
data2000['PLGENAOO'] = other1

C:\Users\piyus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [27]:
other2 = data2000['PLOFPR'] + data2000['PLSWPR']

In [28]:
data2000['PLOOPR'] = other2

C:\Users\piyus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [29]:
data2000 = data2000.drop(columns=['PLOFPR','PLSWPR','PLGENAOF','PLGENASW'])

In [30]:
data2000

,PSTATABB,PNAME,LAT,LON,PLNGENAN,PLGENACL,PLGENAOL,PLGENAGS,PLGENANC,PLGENAHY,...,PLNCPR,PLHYPR,PLBMPR,PLWIPR,PLSOPR,PLGTPR,PLTNPR,PLTRPR,PLGENAOO,PLOOPR
0,AK,AGRIUM KENAI NITROGEN OPERATIONS,60.0656,151.6719,114490.6,0.0,0.0,114490.6,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
1,AK,ALAKANUK,60.2992,159.7343,1474.0,0.0,1474.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
2,AK,ALLAKAKET,64.8557,146.2789,570.0,0.0,570.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
3,AK,ALYESKA SEAFOODS INC,51.9961,175.5654,10717.4,0.0,10717.4,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
4,AK,AMBLER,NaN,NaN,1130.0,0.0,1130.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4696,WY,SINCLAIR OIL REFINERY,41.7170,106.9999,11650.2,0.0,2297.2,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,9353.0,NaN
4697,WY,SPIRIT MOUNTAIN,44.4095,109.8025,14757.0,0.0,0.0,0.0,0.0,14757.0,...,0.0,100.0,0.0,0,0.0,0,0.0,100.0,0.0,NaN
4698,WY,STRAWBERRY CREEK,42.4468,110.5460,9500.0,0.0,0.0,0.0,0.0,9500.0,...,0.0,100.0,0.0,0,0.0,0,0.0,100.0,0.0,NaN
4699,WY,VIVA NAUGHTON,42.4468,110.5460,815.0,0.0,0.0,0.0,0.0,815.0,...,0.0,100.0,0.0,0,0.0,0,0.0,100.0,0.0,NaN
4700,WY,WYODAK,44.2833,105.4000,2664945.0,2662685.0,2260.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN

In [31]:
data2000['PSTATABB'] = data2000['PSTATABB'].map(states).fillna(data2000['PSTATABB'])

In [32]:
data2000

,PSTATABB,PNAME,LAT,LON,PLNGENAN,PLGENACL,PLGENAOL,PLGENAGS,PLGENANC,PLGENAHY,...,PLNCPR,PLHYPR,PLBMPR,PLWIPR,PLSOPR,PLGTPR,PLTNPR,PLTRPR,PLGENAOO,PLOOPR
0,Alaska,AGRIUM KENAI NITROGEN OPERATIONS,60.0656,151.6719,114490.6,0.0,0.0,114490.6,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
1,Alaska,ALAKANUK,60.2992,159.7343,1474.0,0.0,1474.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
2,Alaska,ALLAKAKET,64.8557,146.2789,570.0,0.0,570.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
3,Alaska,ALYESKA SEAFOODS INC,51.9961,175.5654,10717.4,0.0,10717.4,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
4,Alaska,AMBLER,NaN,NaN,1130.0,0.0,1130.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4696,Wyoming,SINCLAIR OIL REFINERY,41.7170,106.9999,11650.2,0.0,2297.2,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,9353.0,NaN
4697,Wyoming,SPIRIT MOUNTAIN,44.4095,109.8025,14757.0,0.0,0.0,0.0,0.0,14757.0,...,0.0,100.0,0.0,0,0.0,0,0.0,100.0,0.0,NaN
4698,Wyoming,STRAWBERRY CREEK,42.4468,110.5460,9500.0,0.0,0.0,0.0,0.0,9500.0,...,0.0,100.0,0.0,0,0.0,0,0.0,100.0,0.0,NaN
4699,Wyoming,VIVA NAUGHTON,42.4468,110.5460,815.0,0.0,0.0,0.0,0.0,815.0,...,0.0,100.0,0.0,0,0.0,0,0.0,100.0,0.0,NaN
4700,Wyoming,WYODAK,44.2833,105.4000,2664945.0,2662685.0,2260.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN

In [33]:
data2000['LON'] = data2000['LON'].multiply(-1)

In [34]:
data2000

,PSTATABB,PNAME,LAT,LON,PLNGENAN,PLGENACL,PLGENAOL,PLGENAGS,PLGENANC,PLGENAHY,...,PLNCPR,PLHYPR,PLBMPR,PLWIPR,PLSOPR,PLGTPR,PLTNPR,PLTRPR,PLGENAOO,PLOOPR
0,Alaska,AGRIUM KENAI NITROGEN OPERATIONS,60.0656,-151.6719,114490.6,0.0,0.0,114490.6,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
1,Alaska,ALAKANUK,60.2992,-159.7343,1474.0,0.0,1474.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
2,Alaska,ALLAKAKET,64.8557,-146.2789,570.0,0.0,570.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
3,Alaska,ALYESKA SEAFOODS INC,51.9961,-175.5654,10717.4,0.0,10717.4,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
4,Alaska,AMBLER,NaN,NaN,1130.0,0.0,1130.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4696,Wyoming,SINCLAIR OIL REFINERY,41.7170,-106.9999,11650.2,0.0,2297.2,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,9353.0,NaN
4697,Wyoming,SPIRIT MOUNTAIN,44.4095,-109.8025,14757.0,0.0,0.0,0.0,0.0,14757.0,...,0.0,100.0,0.0,0,0.0,0,0.0,100.0,0.0,NaN
4698,Wyoming,STRAWBERRY CREEK,42.4468,-110.5460,9500.0,0.0,0.0,0.0,0.0,9500.0,...,0.0,100.0,0.0,0,0.0,0,0.0,100.0,0.0,NaN
4699,Wyoming,VIVA NAUGHTON,42.4468,-110.5460,815.0,0.0,0.0,0.0,0.0,815.0,...,0.0,100.0,0.0,0,0.0,0,0.0,100.0,0.0,NaN
4700,Wyoming,WYODAK,44.2833,-105.4000,2664945.0,2662685.0,2260.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0,100.0,0.0,0.0,NaN

In [35]:
data2000.to_excel(r'C:\Users\piyus\Downloads\2000sort.xlsx')

In [36]:
df3 = pd.read_excel(r'C:\Users\piyus\Downloads\egrid2018_historical_files_since_1996\eGRID2010_Data.xls',header=[1], sheet_name='PLNT10')

In [37]:
data2010= df3[['PSTATABB','PNAME','LAT','LON','PLNGENAN','PLGENACL','PLGENAOL','PLGENAGS','PLGENANC','PLGENAHY','PLGENABM','PLGENAWI','PLGENASO','PLGENAGT','PLGENAOF','PLGENAOP','PLGENATN','PLGENATR','PLCLPR','PLOLPR','PLGSPR','PLNCPR','PLHYPR','PLBMPR','PLWIPR','PLSOPR','PLGTPR','PLOFPR','PLOPPR','PLTNPR','PLTRPR']]

In [38]:
data2010

,PSTATABB,PNAME,LAT,LON,PLNGENAN,PLGENACL,PLGENAOL,PLGENAGS,PLGENANC,PLGENAHY,...,PLNCPR,PLHYPR,PLBMPR,PLWIPR,PLSOPR,PLGTPR,PLOFPR,PLOPPR,PLTNPR,PLTRPR
0,AK,Alakanuk,62.6833,-164.6544,1859.0,0.000,1859.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,100.0,0.0
1,AK,Anchorage 1,61.2328,-149.8909,55428.0,0.000,366.529,55061.471,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,100.0,0.0
2,AK,Angoon,57.8425,-134.9772,1928.0,0.000,1928.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,100.0,0.0
3,AK,Aniak,61.5875,-159.5317,2725.0,0.000,2725.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,100.0,0.0
4,AK,Annex Creek,58.3167,-134.0958,26436.0,0.000,0.000,0.000,0.0,26436.0,...,0.0,100.0,0.0,0.0,0.0,0,0.0,0.0,0.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5582,WY,Wygen 1,44.2862,-105.3843,639854.0,638669.782,0.000,1184.218,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,100.0,0.0
5583,WY,Wygen 2,44.2911,-105.3815,729018.0,725733.666,0.000,3284.334,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,100.0,0.0
5584,WY,Wygen III,44.2919,-105.3806,598363.0,595841.502,0.000,2521.498,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,100.0,0.0
5585,WY,Wyodak,44.2886,-105.3847,2564505.0,2560639.857,3865.143,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,100.0,0.0
5586,WY,Wyoming Wind Energy Center,41.2874,-110.5556,332972.0,0.000,0.000,0.000,0.0,0.0,...,0.0,0.0,0.0,100.0,0.0,0,0.0,0.0,0.0,100.0

In [39]:
other1 = data2010['PLGENAOF'] + data2010['PLGENAOP']

In [40]:
data2010['PLGENAOO'] = other1

C:\Users\piyus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [41]:
other2 = data2010['PLOFPR'] + data2010['PLOPPR']

In [42]:
data2010['PLOOPR'] = other2

C:\Users\piyus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [43]:
data2010 = data2010.drop(columns=['PLOFPR','PLOPPR','PLGENAOF','PLGENAOP'])

In [44]:
data2010

,PSTATABB,PNAME,LAT,LON,PLNGENAN,PLGENACL,PLGENAOL,PLGENAGS,PLGENANC,PLGENAHY,...,PLNCPR,PLHYPR,PLBMPR,PLWIPR,PLSOPR,PLGTPR,PLTNPR,PLTRPR,PLGENAOO,PLOOPR
0,AK,Alakanuk,62.6833,-164.6544,1859.0,0.000,1859.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
1,AK,Anchorage 1,61.2328,-149.8909,55428.0,0.000,366.529,55061.471,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
2,AK,Angoon,57.8425,-134.9772,1928.0,0.000,1928.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
3,AK,Aniak,61.5875,-159.5317,2725.0,0.000,2725.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
4,AK,Annex Creek,58.3167,-134.0958,26436.0,0.000,0.000,0.000,0.0,26436.0,...,0.0,100.0,0.0,0.0,0.0,0,0.0,100.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5582,WY,Wygen 1,44.2862,-105.3843,639854.0,638669.782,0.000,1184.218,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
5583,WY,Wygen 2,44.2911,-105.3815,729018.0,725733.666,0.000,3284.334,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
5584,WY,Wygen III,44.2919,-105.3806,598363.0,595841.502,0.000,2521.498,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
5585,WY,Wyodak,44.2886,-105.3847,2564505.0,2560639.857,3865.143,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
5586,WY,Wyoming Wind Energy Center,41.2874,-110.5556,332972.0,0.000,0.000,0.000,0.0,0.0,...,0.0,0.0,0.0,100.0,0.0,0,0.0,100.0,0.0,0.0

In [45]:
data2010['PSTATABB'] = data2010['PSTATABB'].map(states).fillna(data2010['PSTATABB'])

In [46]:
data2010

,PSTATABB,PNAME,LAT,LON,PLNGENAN,PLGENACL,PLGENAOL,PLGENAGS,PLGENANC,PLGENAHY,...,PLNCPR,PLHYPR,PLBMPR,PLWIPR,PLSOPR,PLGTPR,PLTNPR,PLTRPR,PLGENAOO,PLOOPR
0,Alaska,Alakanuk,62.6833,-164.6544,1859.0,0.000,1859.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
1,Alaska,Anchorage 1,61.2328,-149.8909,55428.0,0.000,366.529,55061.471,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
2,Alaska,Angoon,57.8425,-134.9772,1928.0,0.000,1928.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
3,Alaska,Aniak,61.5875,-159.5317,2725.0,0.000,2725.000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
4,Alaska,Annex Creek,58.3167,-134.0958,26436.0,0.000,0.000,0.000,0.0,26436.0,...,0.0,100.0,0.0,0.0,0.0,0,0.0,100.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5582,Wyoming,Wygen 1,44.2862,-105.3843,639854.0,638669.782,0.000,1184.218,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
5583,Wyoming,Wygen 2,44.2911,-105.3815,729018.0,725733.666,0.000,3284.334,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
5584,Wyoming,Wygen III,44.2919,-105.3806,598363.0,595841.502,0.000,2521.498,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
5585,Wyoming,Wyodak,44.2886,-105.3847,2564505.0,2560639.857,3865.143,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,100.0,0.0,0.0,0.0
5586,Wyoming,Wyoming Wind Energy Center,41.2874,-110.5556,332972.0,0.000,0.000,0.000,0.0,0.0,...,0.0,0.0,0.0,100.0,0.0,0,0.0,100.0,0.0,0.0

In [47]:
data2010.to_excel(r'C:\Users\piyus\Downloads\2010sort.xlsx')